steps:
 - name: 'gcr.io/cloud-builders/git'
   entrypoint: 'bash'
   args: ['clone', 'https://${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}@github.com/rishi-devops1/repo-1']
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/${_PROJECTID}/${_CINAME}:${_VERSION}', '.']
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/${_PROJECTID}/${_CINAME}:${_VERSION}']
substitutions:
 _PROJECTID: dark-quasar-440810-i4
 _CINAME: gke-image
 _VERSION: V1.0
logsBucket: 'gs://cicdbucket1' 


