steps:
 - name: 'gcr.io/cloud-builders/git'
   args: ['clone', 'https://github.com/rishi-devops1/repo-1']
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/${PROJECTID}/${CINAME}:${VERSION}', '.']
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/${PROJECTID}/${CINAME}:${VERSION}', '.']
substitutions:
 PROJECTID: dark-quasar-440810-i4
 CINAME: gke-image
 VERSION: V1.0
options:
logging: NONE



